# A string used to distinguish different Supabase projects on the same machine.
# Not important for remote deployments
project_id = "nextjs-supabase-viem-starter"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000
[api.port]
# Compatibility with legacy config
port = 54321

[db]
# The database port to connect to. Change this if your database is running on a non-standard port.
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anon_sign_ins = false

[edge_runtime]
enabled = true
port = 54333
